# Generated by Django 4.0.2 on 2022-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitemsmodel',
            name='vendor_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
