# Generated by Django 4.0.2 on 2022-05-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_price_ordermodel_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemsmodel',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='orderitemsmodel',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_price',
            field=models.FloatField(default=0),
        ),
    ]
